name: SonarCloud Analysis

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리에서 코드 체크아웃
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # 2. Gradle 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 3. SonarCloud 캐싱
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4. Gradle 권한 변경
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 5. SonarCloud 분석 (커버리지 연동)
      - name: Build, Test, and Analyze (SonarCloud)
        run: ./gradlew build jacocoTestReport sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}